webtalk_init -webtalk_dir /mnt/hgfs/share/k7gggg/tt_hdb3/tt_hdb3.sim/sim_1/behav/xsim/xsim.dir/tbw_test_top_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Mar 10 15:48:52 2023" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211254909_0_0_341" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "a28e60e5-d6b2-4c9c-a35f-a74d6bf36347" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "5404f7ca3c0640bb8383b5b2760e611e" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 16.04.4 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Celeron(R) J4125 CPU @ 2.00GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1996.798 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "3" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.08_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "124556_KB" -context "xsim\\usage"
webtalk_transmit -clientid 774962373 -regid "211254909_0_0_341" -xml /mnt/hgfs/share/k7gggg/tt_hdb3/tt_hdb3.sim/sim_1/behav/xsim/xsim.dir/tbw_test_top_behav/webtalk/usage_statistics_ext_xsim.xml -html /mnt/hgfs/share/k7gggg/tt_hdb3/tt_hdb3.sim/sim_1/behav/xsim/xsim.dir/tbw_test_top_behav/webtalk/usage_statistics_ext_xsim.html -wdm /mnt/hgfs/share/k7gggg/tt_hdb3/tt_hdb3.sim/sim_1/behav/xsim/xsim.dir/tbw_test_top_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
